In [1]:
import numpy as np

In [2]:
arr = np.array([45,52,36,14])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(4,)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr2 = np.array([[45,23,14,69],[52,20,14,15]])
arr2

array([[45, 23, 14, 69],
       [52, 20, 14, 15]])

In [7]:
arr2.ndim 

2

In [8]:
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
#an array that are evenly space btwn a stating no and ending no
np.linspace(10,30,15) # it will bring only 15 numbers


array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        , 21.42857143, 22.85714286,
       24.28571429, 25.71428571, 27.14285714, 28.57142857, 30.        ])

In [11]:
np.linspace(10,30,15 ,dtype = 'int')#if you dont want it to be in float then you specifier the dtype

array([10, 11, 12, 14, 15, 17, 18, 20, 21, 22, 24, 25, 27, 28, 30])

In [12]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
np.zeros(14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.eye(6)#it generate an array 1 as diagonal and zero else where

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(1,101,5)#how to use range

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [16]:
np.random.randint(10,45)#how to randomly generate a number

20

In [17]:
np.random.randint(10,45,70)

array([12, 40, 31, 38, 15, 31, 40, 41, 34, 32, 36, 34, 43, 42, 19, 24, 40,
       30, 10, 23, 44, 38, 42, 29, 31, 30, 27, 44, 42, 44, 17, 44, 43, 25,
       33, 30, 15, 40, 14, 33, 16, 40, 25, 34, 25, 22, 10, 38, 36, 38, 32,
       25, 14, 17, 38, 20, 17, 12, 25, 18, 18, 26, 29, 43, 20, 43, 31, 36,
       34, 22])

In [18]:
np.random.seed(1) # seed allows us to have dxm figure or output
np.random.randint(10,45,70)

array([22, 18, 19, 21, 15, 25, 10, 26, 11, 22, 17, 16, 35, 30, 28, 30, 21,
       38, 39, 24, 14, 33, 33, 40, 42, 32, 23, 19, 17, 32, 11, 10, 27, 18,
       34, 23, 18, 40, 17, 13, 16, 31, 13, 14, 34, 22, 36, 26, 28, 25, 10,
       14, 35, 44, 33, 17, 36, 35, 32, 19, 13, 33, 37, 29, 18, 42, 44, 20,
       33, 25])

In [19]:
num =np.random.randint(10,45,70)


In [20]:
num

array([33, 35, 17, 38, 20, 42, 34, 33, 11, 23, 13, 10, 23, 16, 31, 16, 12,
       22, 37, 31, 21, 17, 23, 18, 21, 22, 30, 40, 17, 14, 28, 42, 23, 20,
       33, 27, 17, 34, 20, 38, 30, 42, 22, 11, 40, 34, 28, 43, 12, 38, 44,
       20, 42, 28, 32, 16, 12, 17, 25, 15, 27, 30, 32, 23, 43, 30, 20, 42,
       35, 31])

In [21]:
num = num.reshape(10,7)
num

array([[33, 35, 17, 38, 20, 42, 34],
       [33, 11, 23, 13, 10, 23, 16],
       [31, 16, 12, 22, 37, 31, 21],
       [17, 23, 18, 21, 22, 30, 40],
       [17, 14, 28, 42, 23, 20, 33],
       [27, 17, 34, 20, 38, 30, 42],
       [22, 11, 40, 34, 28, 43, 12],
       [38, 44, 20, 42, 28, 32, 16],
       [12, 17, 25, 15, 27, 30, 32],
       [23, 43, 30, 20, 42, 35, 31]])

In [22]:
#how to select a value, know the index location of the row and then the column
num[3,3]

21

In [23]:
#how to select a range of value, you must know the index location of the stating row and the ending row then the column
num[3:8,2:5]

array([[18, 21, 22],
       [28, 42, 23],
       [34, 20, 38],
       [40, 34, 28],
       [20, 42, 28]])

In [24]:
#BROADCASTING:broadcasting a SINGLE VALUE all OVER SELECTED VALUES
num[3:8,2:5] = 20
num

array([[33, 35, 17, 38, 20, 42, 34],
       [33, 11, 23, 13, 10, 23, 16],
       [31, 16, 12, 22, 37, 31, 21],
       [17, 23, 20, 20, 20, 30, 40],
       [17, 14, 20, 20, 20, 20, 33],
       [27, 17, 20, 20, 20, 30, 42],
       [22, 11, 20, 20, 20, 43, 12],
       [38, 44, 20, 20, 20, 32, 16],
       [12, 17, 25, 15, 27, 30, 32],
       [23, 43, 30, 20, 42, 35, 31]])

In [25]:
#conditional selection: using conditions to select some values
num[num >30]

array([33, 35, 38, 42, 34, 33, 31, 37, 31, 40, 33, 42, 43, 38, 44, 32, 32,
       43, 42, 35, 31])

In [26]:
np.sum(num)

1728

In [27]:
np.max(num)

44

In [28]:
np.min(num)

10

In [29]:
np.sqrt(num)

array([[5.74456265, 5.91607978, 4.12310563, 6.164414  , 4.47213595,
        6.4807407 , 5.83095189],
       [5.74456265, 3.31662479, 4.79583152, 3.60555128, 3.16227766,
        4.79583152, 4.        ],
       [5.56776436, 4.        , 3.46410162, 4.69041576, 6.08276253,
        5.56776436, 4.58257569],
       [4.12310563, 4.79583152, 4.47213595, 4.47213595, 4.47213595,
        5.47722558, 6.32455532],
       [4.12310563, 3.74165739, 4.47213595, 4.47213595, 4.47213595,
        4.47213595, 5.74456265],
       [5.19615242, 4.12310563, 4.47213595, 4.47213595, 4.47213595,
        5.47722558, 6.4807407 ],
       [4.69041576, 3.31662479, 4.47213595, 4.47213595, 4.47213595,
        6.55743852, 3.46410162],
       [6.164414  , 6.63324958, 4.47213595, 4.47213595, 4.47213595,
        5.65685425, 4.        ],
       [3.46410162, 4.12310563, 5.        , 3.87298335, 5.19615242,
        5.47722558, 5.65685425],
       [4.79583152, 6.55743852, 5.47722558, 4.47213595, 6.4807407 ,
        5.91607978, 5.5

In [30]:
np.mean(num)

24.685714285714287

In [31]:
np.median(num)

20.5

In [32]:
np.log(num)

array([[3.49650756, 3.55534806, 2.83321334, 3.63758616, 2.99573227,
        3.73766962, 3.52636052],
       [3.49650756, 2.39789527, 3.13549422, 2.56494936, 2.30258509,
        3.13549422, 2.77258872],
       [3.4339872 , 2.77258872, 2.48490665, 3.09104245, 3.61091791,
        3.4339872 , 3.04452244],
       [2.83321334, 3.13549422, 2.99573227, 2.99573227, 2.99573227,
        3.40119738, 3.68887945],
       [2.83321334, 2.63905733, 2.99573227, 2.99573227, 2.99573227,
        2.99573227, 3.49650756],
       [3.29583687, 2.83321334, 2.99573227, 2.99573227, 2.99573227,
        3.40119738, 3.73766962],
       [3.09104245, 2.39789527, 2.99573227, 2.99573227, 2.99573227,
        3.76120012, 2.48490665],
       [3.63758616, 3.78418963, 2.99573227, 2.99573227, 2.99573227,
        3.4657359 , 2.77258872],
       [2.48490665, 2.83321334, 3.21887582, 2.7080502 , 3.29583687,
        3.40119738, 3.4657359 ],
       [3.13549422, 3.76120012, 3.40119738, 2.99573227, 3.73766962,
        3.55534806, 3.4

In [33]:
np.argmin(num)

11

In [34]:
np.argmax(num)

50

In [35]:
#how to return d 2D BACK TO 1 DIMENSIONAL ARRAY (FLATTEN)
num = num.flatten()
num


array([33, 35, 17, 38, 20, 42, 34, 33, 11, 23, 13, 10, 23, 16, 31, 16, 12,
       22, 37, 31, 21, 17, 23, 20, 20, 20, 30, 40, 17, 14, 20, 20, 20, 20,
       33, 27, 17, 20, 20, 20, 30, 42, 22, 11, 20, 20, 20, 43, 12, 38, 44,
       20, 20, 20, 32, 16, 12, 17, 25, 15, 27, 30, 32, 23, 43, 30, 20, 42,
       35, 31])

In [36]:
#EXERCISE
#generate an array consisting of 100 numbers between 25 55 reshape the array to 10 row and 10 columns using seed number 7
#return the  value on 3:6 on the row and 5:8 on the column
#broadcast 32 all over the selected areA
#find the mean , min,max,sum, the 50 and 75 percentile

In [37]:
import numpy as np
np.random.seed(7)
num1 =np.random.randint(25,55,100)
num1

array([40, 29, 50, 47, 28, 44, 48, 32, 53, 50, 39, 48, 33, 50, 39, 35, 51,
       33, 32, 31, 29, 41, 32, 37, 25, 36, 48, 51, 31, 44, 53, 37, 30, 49,
       49, 48, 46, 41, 52, 54, 25, 27, 49, 34, 39, 31, 29, 39, 34, 48, 28,
       28, 33, 44, 41, 26, 25, 41, 47, 54, 37, 53, 53, 32, 48, 35, 34, 28,
       25, 54, 32, 48, 53, 48, 25, 46, 29, 28, 26, 28, 52, 52, 26, 44, 52,
       29, 44, 26, 52, 50, 30, 34, 54, 42, 27, 44, 43, 43, 46, 48])

In [38]:

num1 = num1.reshape(10,10)
num1

array([[40, 29, 50, 47, 28, 44, 48, 32, 53, 50],
       [39, 48, 33, 50, 39, 35, 51, 33, 32, 31],
       [29, 41, 32, 37, 25, 36, 48, 51, 31, 44],
       [53, 37, 30, 49, 49, 48, 46, 41, 52, 54],
       [25, 27, 49, 34, 39, 31, 29, 39, 34, 48],
       [28, 28, 33, 44, 41, 26, 25, 41, 47, 54],
       [37, 53, 53, 32, 48, 35, 34, 28, 25, 54],
       [32, 48, 53, 48, 25, 46, 29, 28, 26, 28],
       [52, 52, 26, 44, 52, 29, 44, 26, 52, 50],
       [30, 34, 54, 42, 27, 44, 43, 43, 46, 48]])

In [39]:
num1[3:6,5:8]

array([[48, 46, 41],
       [31, 29, 39],
       [26, 25, 41]])

In [40]:
num1[3:6,5:8] =32
num1

array([[40, 29, 50, 47, 28, 44, 48, 32, 53, 50],
       [39, 48, 33, 50, 39, 35, 51, 33, 32, 31],
       [29, 41, 32, 37, 25, 36, 48, 51, 31, 44],
       [53, 37, 30, 49, 49, 32, 32, 32, 52, 54],
       [25, 27, 49, 34, 39, 32, 32, 32, 34, 48],
       [28, 28, 33, 44, 41, 32, 32, 32, 47, 54],
       [37, 53, 53, 32, 48, 35, 34, 28, 25, 54],
       [32, 48, 53, 48, 25, 46, 29, 28, 26, 28],
       [52, 52, 26, 44, 52, 29, 44, 26, 52, 50],
       [30, 34, 54, 42, 27, 44, 43, 43, 46, 48]])

In [41]:
np.mean(num1)

39.29

In [42]:
np.median(num1)

38.0

In [43]:
import pandas as pd

In [44]:
np.percentile(num1,50)

38.0

In [45]:
np.percentile(num1,75)

48.0

In [46]:
fruits= ['Mango','Grape','Pears','Pineapple']#set lebel
stock = [500,700,45,25]
s1 = pd.Series(data=stock,index=fruits)
s1

Mango        500
Grape        700
Pears         45
Pineapple     25
dtype: int64

In [47]:
s1['Pears']

45

In [48]:
s1 = pd.Series(data=stock)#default lebel
s1

0    500
1    700
2     45
3     25
dtype: int64